services:
  db:
    container_name: db-postgres16
    image: postgres:16-alpine
    #image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: api_db
      POSTGRES_PASSWORD: root
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - springcloud

  app:
    container_name: app
    # image: georgegxx/api-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
#    environment:
#      PORT: 8080
#      DATABASE_URL: jdbc:postgresql://db-postgres14:5432/api_db
#      DATABASE_HOST: db-postgres14:5432
#      DATABASE_DB: api_db
#      DATABASE_USERNAME: postgres
#      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - springcloud
    depends_on:
      - db
    restart: unless-stopped

volumes:
  data-postgres:

networks:
  springcloud:
